---
- name: file module
  hosts: all
  become: true
  tasks:
    - name: creating a file
      file:
        path: /tmp/frommaster.txt
        state: touch
        owner: ubuntu
        mode: u=rwx

    - name: creating a directory
      file:
        path: /tmp/myfolder
        state: directory

...
