---
- name: set password
  hosts: all
  become: true
  tasks:
    - name: setpassword
      user:
        name: suprith
        update_password: always
        password: "{{'asdf123' | password_hash('passlib')}}"

...
